# Generated by Django 5.0 on 2023-12-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_item_description_alter_item_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='trailer',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='watch',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='genre',
            field=models.CharField(choices=[('Драма', 'Драма'), ('Ужасы', 'Ужасы'), ('Экшен', 'Экшен'), ('Слэшер', 'Слэшер'), ('Криминал', 'Криминал')], max_length=54),
        ),
    ]
