# Generated by Django 5.0 on 2023-12-17 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tv_hows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Введите название сериала')),
                ('image', models.ImageField(upload_to='tv_shows/', verbose_name='Добавьте изображение')),
                ('description', models.TextField(blank=True, verbose_name='Введите описание сериала')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Введите стоимость')),
                ('genre', models.CharField(blank=True, choices=[('Хоррор', 'Хоррор'), ('Комедия', 'Комедия'), ('Драма', 'Драма'), ('Экшен', 'Экшен'), ('Фантастика', 'Фантастика')], max_length=50)),
                ('author', models.CharField(max_length=100, verbose_name='Введите имя автора сериала')),
                ('trailer', models.URLField(blank=True, verbose_name='Введите ссылку на трейлер сериала')),
            ],
        ),
    ]
