# Generated by Django 5.0 on 2023-12-17 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tv_hows',
            new_name='Tv_shows',
        ),
    ]
